# Generated by Django 3.2.16 on 2025-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referred_by_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='دعوت شده توسط'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا'),
        ),
    ]
