# Generated by Django 3.2.16 on 2025-03-31 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True, verbose_name='شماره وام')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ وام')),
                ('installment_count', models.IntegerField(verbose_name='تعداد اقساط')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('max_participants', models.IntegerField(verbose_name='حداکثر تعداد ثبت\u200cنام')),
                ('current_participants', models.IntegerField(default=0, verbose_name='تعداد فعلی ثبت\u200cنام')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.01, max_digits=5, verbose_name='نرخ کارمزد')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته'), ('completed', 'تکمیل\u200cشده')], default='open', max_length=20, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='PromissoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan', verbose_name='وام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ قسط')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan', verbose_name='وام')),
            ],
        ),
    ]
